baseURL = "https://en.maku.blog/"
relativeurls = true
enableRobotsTXT = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "ja-jp"
title = "まくまく英語ノート"
# googleAnalytics = "UA-63069513-3"
googleAnalytics = "G-3LHP8YJWGJ"

[markup.goldmark.renderer]
  unsafe = true

[params]
  facebookAppId = "985535638821846"
  Author = "まく"
  AmazonId = "maku04-22"
  CustomSearchId = "partner-pub-6317852277883092:1454758106"

[module]
  [[module.imports]]
    path = "github.com/maku77/hugo-module-maku-common"
  [[module.imports]]
    path = "github.com/maku77/hugo-module-maku-blog"

